@startuml Visão Geral
    title <b>Visão Geral do Processo de Reaproveitamento de Disciplinas</b>

    !includesub reaproveitamento-disciplina-visao-discente.puml!DISC
    !includesub reaproveitamento-disciplina-visao-escolaridade.puml!ESCO
    !includesub reaproveitamento-disciplina-visao-coordenacao.puml!COORD
    
@enduml

